SELECT SALES.ISBN, Title, COUNT(*) FROM SALES JOIN BOOK ON  SALES.ISBN = BOOK.ISBN
WHERE MONTH(Purchase_date) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH)
GROUP BY SALES.ISBN, Title;

SELECT Customer_name , COUNT(*) FROM SALES
GROUP BY Customer_name
ORDER BY COUNT(*) DESC LIMIT 5;

SELECT SALES.ISBN, Title, COUNT(*) FROM SALES JOIN BOOK ON  SALES.ISBN = BOOK.ISBN
GROUP BY SALES.ISBN, Title
ORDER BY COUNT(*) LIMIT 10;

SELECT COUNT(*), SUM(Selling_Price) FROM SALES JOIN BOOK ON  SALES.ISBN = BOOK.ISBN
WHERE MONTH(Purchase_date) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH);